### ISSUE TITLE
longevity fails on bootsrap repo

### ISSUE THREAD

**Issue by osilla** [sourcerer-io/sourcerer-app#134]
[e] No line at 35; commit: 6a0a139cdabe9ad24f2dcee3044bb62f8738df15; 'Upgrade to Normalize v3-rc1 in prep for v3 final': Index: 35, Size: 35
java.lang.IndexOutOfBoundsException: Index: 35, Size: 35

**Comment by anatolystansler** [comment]
We don't calculate code longevity anymore.
