### ISSUE TITLE
Longevity fails on some repos due to JGit exceptions

### ISSUE THREAD

**Issue by osilla** [sourcerer-io/sourcerer-app#137]
Example errors:
Hashing error: Missing unknown b3de5226c057d0588316c8bb0450990605e035d1
https://github.com/persiyanov/AgentNet
Error while hashing: Missing unknown fb714b3606bd663b823f6960a73d052f97283b74
https://github.com/persiyanov/temporal-topic-models-bigartm/
Fixes for CommitCrawler for the same errors: commit
Dirty fixes for LongevityHasher: commit  @asurkov  , take a look

**Comment by anatolystansler** [comment]
We don't calculate code longevity anymore.
