### ISSUE TITLE
Can't reset password

### ISSUE THREAD

**Issue by praxeo** [sourcerer-io/sourcerer-app#143]
I use Lastpass to generate my passwords. Unfortunately, Lastpass did not save the password I generated for my Sourcerer account, so I am stuck when running the sourcerer script on my computer. I see no mechanism on the website to get my password reset. Is this a bug?

**Comment by sergey-surkov** [comment]
Hi Benjamin,

Sorry for the inconvenience. We did not implement a proper password reset yet. Could you please use this js fiddle to hash your password and send the output to support@sourcerer.io along with your username?

https://jsfiddle.net/uh47wag3/

Thank you!

**Comment by praxeo** [comment]
Consider it done! Thank you for your help!

**Comment by anatolykislov** [comment]
Password reset flow implemented, closing an issue.

**Comment by bk138** [comment]
@anatolystansler Knowing this is an old issue, I can't  find the password reset functionality on sourcerer.io. Can you give a hint please?

**Comment by sibelly** [comment]
Same issue here... and I didn't receive the email with the password... I did enter with github credentials... but it did not accept my password.

**Comment by bk138** [comment]
@sibelly see my feature request at #589 on how to solve this.
