### ISSUE TITLE
Uncaught exception: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by klapen** [sourcerer-io/sourcerer-app#161]
Hi,

I re-run sourcerer command to update my repos and got in all of them:

Hashing /path/to/repo repository...
[i] Hashing of repo started.
[i] Received repo from server with X commits.
[e] Error while hashing: java.net.SocketTimeoutException: Read timed out

and in one specially got another error: [e] Error while hashing: 83b6863dbd77fb925402e836b8e913160cfc4d94 exceeds size limit.

Regards,

**Comment by sergey-surkov** [comment]
Hi Orlando,

We will look into it shortly.

Best,
Sergey

**Comment by EdvinasBa** [comment]
I'm having a similar issue with a bigger repo, it receives 0 commits. 
Smaller repos work fine.
```
Hashing /path/to/repo repository...
[i] Hashing of repo started.
[i] Received repo from server with 0 commits.
[e] Error while hashing: java.net.SocketTimeoutException: Read timed out
The repositories have been hashed.
```

**Comment by anatolykislov** [comment]
Hi!

Issue is fixed now. Thank you for contacting us!
