### ISSUE TITLE
(Stats) Ruby not being listed in languages

### ISSUE THREAD

**Issue by osilla** [sourcerer-io/sourcerer-app#163]
User has informed me that he thinks the app skipped over 2 Ruby on Rails projects he added.  In the "Technologies" section it shows Rails but in the "Languages" section it doesn't mention Ruby at all.

His profile:
https://sourcerer.io/rwoliver2

**Comment by yaronskaya** [comment]
It looks like ruby is not in top6 languages. So we don't show it in profile.
