### ISSUE TITLE
User committed in Prolog differently than what we report

### ISSUE THREAD

**Issue by osilla** [sourcerer-io/sourcerer-app#175]
The following user wrote to me

> Well, considering that I don't write in prolog, but did commit in November and December 2017, the outcome does not inspire confidence.

https://sourcerer.io/vfonov

if you look at his profile we detect prolog in 2011 and 2015

**Comment by anatolykislov** [comment]
Issue with Prolog resolved, profile cleaned.
Missed commits in November and December require further investigation.

**Comment by anatolystansler** [comment]
Probably related to not assigned email. Closing for now.
