### ISSUE TITLE
Convert from github created user to have user/password

### ISSUE THREAD

**Issue by Bored0ne** [sourcerer-io/sourcerer-app#188]
I created a new account on sourcerer using my github. Now I can't use the app to track my own private repos using my logged in account because I don't have a username/password I have a github sso. I must be doing something wrong but if not, how do I log in to the app?

**Comment by osilla** [comment]
hi there - you should have received an email with a temporary password. you can use that along with the email that was associated with your github sso that we sent it too.  please let me know if you still have issues.
