### ISSUE TITLE
(Stats) Missing repos on profile from user feedback

### ISSUE THREAD

**Issue by osilla** [sourcerer-io/sourcerer-app#189]
The following user has mentioned that he has many repos that are not being added to his profile.

https://sourcerer.io/mightyiam
https://github.com/mightyiam

**Comment by anatolystansler** [comment]
@mightyiam we've reprocessed your profile check it :) https://sourcerer.io/mightyiam

it took some time
![slowpoke-logo-0951a87e3f-seeklogo com](https://user-images.githubusercontent.com/29913247/43478628-06209bb2-9507-11e8-8c0d-856536ccd4d6.png)
