### ISSUE TITLE
Profile Not Displaying Data

### ISSUE THREAD

**Issue by walshyb** [sourcerer-io/sourcerer-app#191]
I didn't see another issue where this has happened, but after adding repositories locally, my profile didn't update even though after running the app it said the updates are on my profile.  

What I did:
- I added 7 local repositories to track using `sourcerer add the/path`
- Ran `sourcerer`

Things I checked:
- That I was logged in successfully (`Signed in successfully. Your profile page is https://sourcerer.io/bwalshy [i] Auth success.`)
- That the app ran without any errors
- That all the repos I added were being tracked
- That I got the email saying my Sourcerer profile is ready

If there's anything you need from me, just let me know!

**Comment by anatolykislov** [comment]
Hi @walshyb!
Please make sure that you've specified all emails that you use for committing. You can check a list of your emails in [Settings page](https://sourcerer.io/settings) or during execution of the app.
The app will ask you to add emails if you've didn't specify any emails that presented in a repo. If it doesn't run the app with --setup flag to launch setup wizard, and specify your emails.

**Comment by walshyb** [comment]
True! I just noticed that the email I primarily commit with isn't listed on the settings page. However, whenever I ran the app, I got this notice:

```
List of your emails:
primary.email@email.com (Primary) — Confirmed
Your git config contains untracked emails:
other.email@gmail.com
Do you want to add this emails to your account? [Y/n]
Y
Do you want to specify additional emails that you use in repositories? [y/N]
N
Confirm your emails to show all statistics in profile.
[i] Hashing started.
```

I'd always ask if I wanted to add the other email address to my account, but it never sent me an email to confirm my secondary email address.

**Comment by anatolykislov** [comment]
@walshyb sorry for the long delay with the answer!
It seems that all your email addresses are confirmed, are there any problems now?
