### ISSUE TITLE
Tensorflow, etc not detected for a user

### ISSUE THREAD

**Issue by sergey-surkov** [sourcerer-io/sourcerer-app#195]
From a user: To make this data valuable try to analyze the technologies and libraries used Tensorflow Keras Scikit learn or which npm is used and in which frequency

The profile: https://sourcerer.io/yossico

**Comment by yaronskaya** [comment]
The repo that has his commits with techs (this one github.com/yossico/CarND-Semantic-Segmentation) is not processed by us because it has the size >100 mb. He should use the app to get the technology stats. 
Other repos with technology stats don't contain his commits in the master branch.
