### ISSUE TITLE
User is seeing more loc than he should

### ISSUE THREAD

**Issue by osilla** [sourcerer-io/sourcerer-app#197]
the following user wrote to me that

"it's confusing how "Technologies" work - while there is a project I've worked on which uses gdx, whole project counts less than 10k LOC (out of which 5.6k are mine), so I'm not sure how it got to the number of 11k+ lines."

https://sourcerer.io/lukaj

**Comment by anatolykislov** [comment]
We calculate LOC as the sum of added and deleted lines in commits. So it should be slightly bigger than current number of lines in files.
