### ISSUE TITLE
Only 1 repository appears in my account

### ISSUE THREAD

**Issue by kounelios13** [sourcerer-io/sourcerer-app#206]
Hello.
Today I created my account and hashed 3 local repositories.
However only data from the first repo appear in my profile.
Why is this happening?
here is my profile : https://sourcerer.io/mkcdergr

**Comment by sergey-surkov** [comment]
Hi,

We are looking into this. You should expect an answer by the end of
tomorrow.

Best,
Sergey Surkov
cofounder @ sourcerer

**Comment by anatolykislov** [comment]
Hi,

Your account has only one associated email. Looks like you are using a different email for other 2 repos. Please check what email you are using in that repos with git log and add new email using sourcerer app and process repos again.

**Comment by kounelios13** [comment]
No i don't

**Comment by kounelios13** [comment]
sorry my mistake I am using a second email

**Comment by kounelios13** [comment]
so I added the 2nd email but no luck

**Comment by anatolykislov** [comment]
You have 3 repos in your profile now 🙂

**Comment by kounelios13** [comment]
Yes.Can I know what technologies are available for repos?

**Comment by anatolykislov** [comment]
Currently you can see summary of technologies from all of your repos in the Tech section. Would you like to see tech stats per each repo?

**Comment by kounelios13** [comment]
Is that possible?

**Comment by anatolykislov** [comment]
It can be our next feature if you have interest in it. Could you send your suggestions to hello@sourcerer.io?

**Comment by kounelios13** [comment]
Sure .I will find some time later today to send some thoughts
