### ISSUE TITLE
Image of profile

### ISSUE THREAD

**Issue by Sphinxs** [sourcerer-io/sourcerer-app#207]
Add

```
<meta property="og:image" content="*">

<meta property="og:image:type" content="image/png">
 
<meta property="og:image:width" content="795">

<meta property="og:image:height" content="470">
```
On profile page for when someone share his profile ( For example ) sourcerer.io/sphinxs the content looks good 'n not like this :

![](https://i.imgur.com/PeykDsi.png)

**Comment by anatolykislov** [comment]
Hi Sphinxs,

Thank you for suggesting an improvement. We will add meta tags in our future release.

**Comment by anatolykislov** [comment]
Hi @Sphinxs,
Thank you again for creating this issue! We've improved link preview, looks better now.
I'm closing issue now, feel free to reopen it if any additional changes required.
