### ISSUE TITLE
User is getting credit for somebody else's code

### ISSUE THREAD

**Issue by osilla** [sourcerer-io/sourcerer-app#214]
feedback from user:

https://sourcerer.io/carlsson87
--

I have repos where I have committed entire frameworks, and I guess that all of that code is seen as “mine”, which leads to some weird conclusions (for example that I prefer tabs over spaces).

**Comment by anatolystansler** [comment]
We add filtering of well-known vendor files: https://github.com/sourcerer-io/sourcerer-app/blob/develop/src/main/kotlin/app/hashers/Vendors.kt

Also, there is base support of stats-ignore config, but we need to update incremental update protocol to it start working properly. @asurkov let's discuss it offline.
