### ISSUE TITLE
Bar graph bins imply that "lines per commit" is zero in most

### ISSUE THREAD

**Issue by BlitzKraft** [sourcerer-io/sourcerer-app#219]
![graph](https://user-images.githubusercontent.com/6516167/36769914-e7875bf0-1c0c-11e8-9021-051640df73f6.png)

I guess most of my commits are between 0 - 230 lines per commit, but the bin labeling could be clearer by translating the zero on x-axis a little bit to the left.

**Comment by anatolykislov** [comment]
Hi, @BlitzKraft !
We are working on this chart now, will be fixed soon. Thank you for good UI suggestion.

**Comment by Thorium** [comment]
I have the same problem. I maintain a few repos and I expect the merge-commits are counted as zero-line-commits? They could be ignored.

**Comment by anatolystansler** [comment]
The chart temporary removed from the profile.
