### ISSUE TITLE
Hashing error

### ISSUE THREAD

**Issue by pkollitsch** [sourcerer-io/sourcerer-app#231]
After seemingly successfully adding local repositories sourcerer scans some repos, but fails to "hash stats".

```
Hashing /home/patrick/Projects/FOLDERNAME repository...
[i] Hashing of repo started.
[i] Received repo from server with 0 commits.
[i] Sent 3 facts to server.
Stats computation. May take a while...
[e] Hashing error: Invalid value: diff.algorithm=patience
[e] Hashing error: Invalid value: diff.algorithm=patience
[e] Error while hashing: Invalid value: diff.algorithm=patience
[e] Error while hashing: Invalid value: diff.algorithm=patience
The repositories have been hashed.
```

This happens to all local profiles.

**Comment by anatolykislov** [comment]
Hi!
Thank you for creating an issue!
Looks like your .gitconfig contains setting for a diff algorithm patience which is not supported by JGit library that we are using to work with git repositories. JGit only supports: myers and histogram diff algorithms. See [JGit Bug 446511](https://bugs.eclipse.org/bugs/show_bug.cgi?id=446511).
You can try using histogram which is extended version of patience.

**Comment by pkollitsch** [comment]
That solved it, thank you!
