### ISSUE TITLE
Pie chart can display the same colours as neighbouring

### ISSUE THREAD

**Issue by wende** [sourcerer-io/sourcerer-app#236]
CoffeeScript and Elm are two different languages but have the same colour and are next to each other

<img width="860" alt="screen shot 2018-03-14 at 14 14 17" src="https://user-images.githubusercontent.com/4634386/37404478-45423f7c-2792-11e8-9baf-97859e4a9ff8.png">

**Comment by anatolykislov** [comment]
Hi!
This is default color. We will add more colors to our palette for languages.
Also, we need to update Elm caption.

**Comment by anatolystansler** [comment]
@wende we've improved colors and titles for all of our supported languages. Give it a try.
