### ISSUE TITLE
"Did you know" section typo

### ISSUE THREAD

**Issue by anselal** [sourcerer-io/sourcerer-app#237]
Hi there,

in the "Did you know" section there is a typo:

I mostly use CamelCase **_overs_** snake_case for naming variables

**Comment by yandzee** [comment]
Hi!
Its kind of you to notify us! We will fix it soon.

**Comment by yandzee** [comment]
Fixed.

**Comment by anselal** [comment]
I don't see a commit that fixes this issue.
Was it a UI typo which is not in the codebase of the project ?

**Comment by yandzee** [comment]
Yes

**Comment by anselal** [comment]
OK
