### ISSUE TITLE
Website processing page shows that all repositories either failed or pending forever

### ISSUE THREAD

**Issue by johann-petrak** [sourcerer-io/sourcerer-app#246]
In Settings->Processing:
Long list of repository links (about 60), each with status "Failed" and reason "Processing error" no information on the profile at all plus about 4 with status "Pending" already for a long time. Not a single one completed successfully.

**Comment by cuducos** [comment]
Same here.

**Comment by anatolykislov** [comment]
Hi! We are working on the problem, it will be resolved soon.
Thank you!

**Comment by cuducos** [comment]
That's great news – many thanks. Please, let me know if I can be of any helping testing anything ; )

**Comment by anatolykislov** [comment]
Hi! The problem was resolved at 30 March, we've tested system for a while and servers working good now. Thank you for patience!
Closing an issue now. Reopen if you still encountering any related problem.

**Comment by rithvikvibhu** [comment]
@anatolystansler Hey, I'm having the same issue with 1 pending and 21 failed (processing error) from GitLab. Could you please take a look?

Here's the current status: https://screenshots.firefox.com/xWI1KQOyvdSDwCjG/sourcerer.io
