### ISSUE TITLE
Do you support private Repos ?

### ISSUE THREAD

**Issue by KyleSponz** [sourcerer-io/sourcerer-app#249]
I have quite a bit of work Im doing in private repos php and its for live websites that is in by github profile but not in my sorcerer profile

**Comment by sergey-surkov** [comment]
Hi Kyle,

We support private repos, but we choose not to ask for private repo access on GitHub to prevent accidental intellectual property leaks. For private repos, you can use our app and run analysis locally. You can build it from the source code at https://sourcerer-io/sourcerer-app, or you can simply use our installer:

curl -s https://sourcerer.io/app/install | bash

The app will ask for a username (this is your github username assuming you registered via github), and a password (which was emailed to you during the registration but you can also change it in settings). Then it will ask you for the repos on your local machine. And then it will look at your code, and will upload stats to the server. Note that your code is not uploaded anywhere, all analysis runs locally.

**Comment by KyleSponz** [comment]
that is pretty sweet nix compatible?

**Comment by KyleSponz** [comment]
I installed the app got it to run and listed my git repo how do I push the results home when I hit refresh nothing happens

**Comment by sergey-surkov** [comment]
The app pushes the results when you run. When the app is running (and reporting its progress hashing repos), you should be able to see the 'processing' banner on top of the profile. And your repos should appear in the list of repos with labels like 'repo 1', 'repo 2', etc. Is this not happening?

The refresh button only updates your public GitHub repos.

**Comment by KyleSponz** [comment]
Not that I can see I have a wordpress repo Ive been doing quite a bit of work to as of late it shows added in the app when I use sourcerer list but does not show up in my profile. 

PS really like the idea, thanks I might try to find a way to embed this in my wordpress site or if you could generate an embed code for it that would be sick!!! Im more a backend guy but if you want to give some guidance Ill help out however I can

**Comment by sergey-surkov** [comment]
Hm... It does not show any private repos in your profile at all. Could you send your ~/.sourcerer/data/config.yaml to me at sergey@sourcerer.io ? Also, could you run the app again, and direct its output to a file and send that to me as well? Thank you!

**Comment by sergey-surkov** [comment]
oh yeah, re, embed code: people are asking. we will see what we can do. what are your thoughts on embedding? what should it be? our logo? some widget with stats?

**Comment by ThisIsJeron** [comment]
definitely widget with stats, like just the main chart would be awesome

also thanks for answering the question about the password, I thought the password had to be requested but sure enough it was in my email inbox

**Comment by dingran** [comment]
I got a timeout error when attempting to use the app to login

~/Downloads » sourcerer                                         
[w] No config file found.
[i] App started.
Sourcerer hashes your git repositories into intelligent engineering profiles.
If you don't have an account, please, sign up at https://sourcerer.io/join
Enter username:
dingran
Enter password:

Signing in...
Connection problems. Try again later.
[e] java.net.SocketTimeoutException: Read timed out

You could use console commands to control repositories.
For more info run application with flag --help.
Feel free to contact us on any problem by support@sourcerer.io.
[i] App finished.
