### ISSUE TITLE
Open Source Report Card

### ISSUE THREAD

**Issue by cleder** [sourcerer-io/sourcerer-app#253]
I quite enjoyed the prose generated by Open Source Report Card
https://github.com/dfm/osrc
could that be integrated?

**Comment by sergey-surkov** [comment]
Christian, http://osrc.dfm.io is down 'due to breaking changes in GitHub' API, so we can't look at it at the moment. If you see there ideas that you want to be implemented in Sourcerer, could you post them here?

**Comment by anatolystansler** [comment]
Hi @cleder 

Closing this issue for now. Feel free to reopen it if there is any updates on http://osrc.dfm.io status, it's down at the moment.
