### ISSUE TITLE
Overview panel tool-tips overlapping

### ISSUE THREAD

**Issue by xorz57** [sourcerer-io/sourcerer-app#262]
![image](https://user-images.githubusercontent.com/1548352/38743727-8042ffa8-3f48-11e8-91bb-cc2d8a402e5f.png)

**Comment by anatolykislov** [comment]
Hi @xorz57!
Thank you for reporting an issue! We will fix it.

**Comment by anatolystansler** [comment]
Hi @xorz57 

We've made a huge refactor of the overview chart, give it a try:
![overview chart](https://user-images.githubusercontent.com/29913247/43473606-4f6ff582-94f9-11e8-85a5-ed55f6909a48.gif)

Closing issue now, feel free to reopen it if you have any comments of suggestions.
