### ISSUE TITLE
user claims technology found in his repo is wrong

### ISSUE THREAD

**Issue by osilla** [sourcerer-io/sourcerer-app#263]
The following user said on twitter "Cool app! One thing though, my "mpnetwork" repo on GitHub (same username) is not CSS, it is Elixir (although there is definitely original CSS present!)"

https://sourcerer.io/pmarreck

**Comment by yaronskaya** [comment]
We've updated the profile. It's showing elixir and scss as tech. 
I'm closing the issue.
