### ISSUE TITLE
After deleting a repository, those should be removed from sourcerer too

### ISSUE THREAD

**Issue by marcosps** [sourcerer-io/sourcerer-app#269]
Right now, I have some repositories that don't exist anymore, but they are still being listed, for example, the tlpi_examples repository:
https://sourcerer.io/marcosps

After deleting the repo, I executed a refresh in the settings menu, but the repository is still being listed... Am I missing something?

**Comment by anatolykislov** [comment]
Hi @marcosps!
Thank you for reporting this issue! We will fix it.

**Comment by yasinuslu** [comment]
I was syncing my intellij and webstorm settings in a github repo in the past, now i look like an XML developer :)

**Comment by outcastdreamer** [comment]
I am also having this problem, my latest repos are not been shown on my profile but my old ones are. It also shows that I have worked the most on HTML and CSS as per my previous deleted repos in the pie chart on my profile page which isn't true anymore. My sourcerer profile is : 
sourcerer.io/outcastdreamer

**Comment by marcosps** [comment]
This bug is still present, and somehow it makes the tool not so useful as it should be, because it shows some work that I wouldn't like to point in my github. Can you guys also create a configuration entry to choose between the repos that would be shown?

**Comment by marcosps** [comment]
I guess the project died, so I'm closing the bug :)
