### ISSUE TITLE
Gradle isn't language but build tool

### ISSUE THREAD

**Issue by kenrube** [sourcerer-io/sourcerer-app#291]
Groovy actually

**Comment by faraazahmad** [comment]
Agreed. My Flutter projects which are around 80% Dart code are shown as using Gradle

**Comment by anatolystansler** [comment]
Hi @kenrube and @faraazahmad !
Thank you for your feedback! We will fix language detection problem.

Also, where do you think we should show gradle statistics and other build tools? What is more suitable additional group in the "tech" section or a new section called "build tools"?

**Comment by kenrube** [comment]
@anatolystansler If you can detect other build tools like `Maven`, `cmake`, `Bazel` and so on, I think "build tools" section would be preferable :)

**Comment by asurkov** [comment]
@faraazahmad Do I understand right that gradle lives in '.gradle' files, dart lives in '.dart' files or are there exceptions?

**Comment by faraazahmad** [comment]
@asurkov yes

**Comment by asurkov** [comment]
@yaronskaya, so @faraazahmad issue has to be something else than lack of Dart support. I believe that sourcerer-app will report Gradle language for anything located in '.gradle' files.

**Comment by yaronskaya** [comment]
@asurkov sure. However, it revealed a missing language.

**Comment by asurkov** [comment]
@yaronskaya check it out for missing languages :) https://github.com/sourcerer-io/sourcerer-app/blob/develop/src/test/kotlin/test/tests/extractors/IgnoredSamplesWildcards.kt

**Comment by kenrube** [comment]
Closed due to inactivity
