### ISSUE TITLE
No data in my profile

### ISSUE THREAD

**Issue by aslafy-z** [sourcerer-io/sourcerer-app#293]
My profile (https://sourcerer.io/aslafy-z) does not shows any content, I did two (successful) scans and it seems that no data went in.
Thank you

**Comment by anatolystansler** [comment]
Hi @aslafy-z !

Fixed your profile (https://sourcerer.io/aslafy-z) manually, now it contains data and looks good. Thank you for creating an issue!

Other profiles may be affected, we are working on fix for this bug.

**Comment by anatolystansler** [comment]
Problem is fixed now.

**Comment by bennygenel** [comment]
@anatolystansler I have a similar problem. 2 of my contributions are not counted (I have so little that it is easy to identify). I have 2 merged PRs to both [zeit/next.js](https://github.com/zeit/next.js) and [sequelize/sequelize](https://github.com/sequelize/sequelize). Do my contributions staying under some sort of minimal limit or something or do I have some sort of missing information?

_Thank you for the project btw._
