### ISSUE TITLE
Some commits are not counted

### ISSUE THREAD

**Issue by chris48s** [sourcerer-io/sourcerer-app#294]
I really like the idea for this project. Great work on it. Unfortunately in some cases it seems commits are not counted.

For example, https://sourcerer.io/chris48s says I have made only one commit to https://github.com/badges/shields (this repo is in 64th position on my list) but in reality I have made many commits to this repo: https://github.com/badges/shields/commits?author=chris48s

Any idea why this happens?

**Comment by anatolystansler** [comment]
Hi @chris48s !

Thank you for the feedback! 😃 

I fixed your profile (https://sourcerer.io/chris48s) manually, now it shows contributions to shields repository (a great project, thank you for it) and other additional statistics too.

It's the same bug as #293. We are working on fixing it.

**Comment by chris48s** [comment]
Thanks for fixing. If this is a straight duplicate of another issue, feel free to close it.

**Comment by fsancheztemprano** [comment]
Hello, i didn't want to open new issue jic...
i believe i have similar issues, my profile 
https://sourcerer.io/fsancheztemprano
says i have 1 contribution to 
https://github.com/fsancheztemprano/YYY_DaLi
but i have nearly 320 commits

am i doing something wrong?
i rescaned several times, deleted my sourcerer account and re created it no fix.
thanks in advanceq
