### ISSUE TITLE
Cake diagram bug

### ISSUE THREAD

**Issue by europ** [sourcerer-io/sourcerer-app#296]
The mouse hover effect (zoom) above the cake diagram does not return the cake parts into their original size.

![cake](https://user-images.githubusercontent.com/22373707/42056380-4c798364-7b1a-11e8-8201-c0ce6f2300ca.gif)

**Comment by sergey-surkov** [comment]
Best bug report ever!
S.

**Comment by anatolystansler** [comment]
Hi @europ !

Thank you for creating of such amazing report! Could you specify what browser and platform do you use?

**Comment by europ** [comment]
**Operating System**:
* `Ubuntu 16.04.4 LTS`
* `Linux 4.13.0-36-generic #40~16.04.1-Ubuntu x86_64 GNU/Linux`

**Browser**:
* `Mozilla Firefox 60.0.2 (64bit)`

**Comment by nukeop** [comment]
I'm seeing the same bug on Firefox Nightly (61).

**Comment by anatolystansler** [comment]
Fixed :)
