### ISSUE TITLE
Element indention bug

### ISSUE THREAD

**Issue by europ** [sourcerer-io/sourcerer-app#297]
First element in the lower row of elements is mis-indented when the elements are moved due to row size change.

![row](https://user-images.githubusercontent.com/22373707/42058089-8d172b60-7b1f-11e8-8f7b-23098f458c1e.png)

![row](https://user-images.githubusercontent.com/22373707/42058057-7169159a-7b1f-11e8-8246-696fe0334548.gif)

Change the zoom level of your browser to reproduce the bug shown in gif above.

**Comment by anatolystansler** [comment]
Hi @europ !

Thank you for showing problem visually! Specify browser and platform, please.

**Comment by europ** [comment]
**Operating System**:
* `Ubuntu 16.04.4 LTS`
* `Linux 4.13.0-36-generic #40~16.04.1-Ubuntu x86_64 GNU/Linux`

**Browser**:
* `Mozilla Firefox 60.0.2 (64bit)`

**Comment by anatolystansler** [comment]
Fixed :)
