### ISSUE TITLE
My profile appears empty

### ISSUE THREAD

**Issue by klaaspieter** [sourcerer-io/sourcerer-app#300]
After two scans my profile is still empty. I believe this is a duplicate of #293 but decided to file a separate issue so the original author isn't notified of changes.

**Comment by anatolystansler** [comment]
Hi @klaaspieter !

Thank you for creating an issue! You are right, it's a duplicate of #293. Fixed your profile manually for now. We working on a fix.

Closing this issue, feel free to reopen it if you still have any problems.
