### ISSUE TITLE
App is out of date. Please get new version at https://sourcerer.io

### ISSUE THREAD

**Issue by dantuluri** [sourcerer-io/sourcerer-app#301]
I just installed sourcerer with `curl -s https://sourcerer.io/app/install | bash`

and everything seems to work fine. I've entered my Github username and password, but I get an "App is out of date." Error everytime I run sourcerer

**Comment by anatolystansler** [comment]
Hi @dantuluri !

Problem fixed, try again, please. Thank you for creation of the issue!
