### ISSUE TITLE
Add several repo with add command

### ISSUE THREAD

**Issue by mathieutu** [sourcerer-io/sourcerer-app#308]
Hi, 
It should be cool to be allowed to add several repo directly with the add command.
For now, we're forced to "add" them one by one.

And if allowed it will be possible to use wildcard too.

```zsh
$ sourcerer add foo bar 
[i] App started.
[e] Uncaught exception: Only one main parameter allowed but found several: "foo" and "bar"

$ sourcerer add projects/*
[i] App started.
[e] Uncaught exception: Only one main parameter allowed but found several: "projects/foo" and "projects/bar"
```

Thanks for your amazing work!

**Comment by anatolystansler** [comment]
Hi @mathieutu 

This is a really good suggestion! We plan to update the app interface in the future and will take this into account.

**Comment by sfat** [comment]
@yaronskaya we can close this, right?

**Comment by yaronskaya** [comment]
@sfat sure
