### ISSUE TITLE
Commits not being attributed correctly

### ISSUE THREAD

**Issue by rshipp** [sourcerer-io/sourcerer-app#311]
Many of my commits processed by Sourcerer are showing up as other people's, under "My commits vs. Average commits". I tried adding more emails I've committed from to my GitHub profile, and re-processing with Sourcerer, but it didn't make a difference.

Here's an example of a repo that shows up on my profile:

![image](https://user-images.githubusercontent.com/1382374/42611069-e5ddc4fe-8559-11e8-80a5-211bb465860a.png)

If you check the repo contributors, only I have commits here: https://github.com/rshipp/pkgbuilds/graphs/contributors

![image](https://user-images.githubusercontent.com/1382374/42611117-28b325f8-855a-11e8-800d-7deffc2f8f6a.png)

Several of the other projects on my Sourcerer profile are the same way, with either zero or a very small number of outside commits showing up as 50-50 split or close to it.

**Comment by sergey-surkov** [comment]
Hi @rshipp ,

Average commits also include your own, so there is nothing wrong with attribution here per se. When you see that your commit number is the same as average commits, this means that all commits are likely yours.

I do see your point though. As it is now, this chart may be confusing. We are currently redesigning it, and will take this into account.

Thank you!

**Comment by rshipp** [comment]
Ah, OK, sorry for the confusion. I'm not sure I understand what the graph is showing still, but I love the UI changes you've been making so far, so I look forward to seeing how this redesign turns out.
