### ISSUE TITLE
Display bug with legend item

### ISSUE THREAD

**Issue by nukeop** [sourcerer-io/sourcerer-app#315]
I found one tiny bug. Looks like one of the items, in my case "react" is displayed incorrectly under the chart. There's an empty line in it that messes up the alignment. Here are some screenshots that illustrate the issue.

![](http://i.imgur.com/Kh3ytQu.png)

With css box model overlaid:
![](https://i.imgur.com/FbakQuC.png)

I'm seeing this on Firefox Nightly 61 on Linux Mint 18.3.
It looks like it has the left margin like the items in the first row, but it doesn't have the top margin like the items in the second row. Removing the left margin moves it back to the first row, which makes me think this is because it's supposed to be in the first row, but adding the margin makes it too large to fit there.

**Comment by anatolystansler** [comment]
Hi @nukeop 
Thank you for reporting it! WIP

**Comment by anatolystansler** [comment]
Should be fixed now, please, check.

**Comment by nukeop** [comment]
Yes, it's fixed.
