### ISSUE TITLE
It isn't displaying my repositories in sourcerer.io/karanrawlley

### ISSUE THREAD

**Issue by KaranRawlley** [sourcerer-io/sourcerer-app#324]
please fix the above mentioned problem

**Comment by anatolystansler** [comment]
Hi @KaranRawlley 

Email that you usually use for claiming of authorship of commits is not assigned to Sourcerer or GitHub profiles. I've assigned it manually and reprocessed your profile.

Have a nice day!

https://sourcerer.io/karanrawlley

**Comment by KaranRawlley** [comment]
Thank you for solving my issue
