### ISSUE TITLE
auth via github is not working

### ISSUE THREAD

**Issue by ORESoftware** [sourcerer-io/sourcerer-app#340]
I get this when I first try to sign up via Github

![screenshot from 2018-08-30 13-38-13](https://user-images.githubusercontent.com/11139560/44877843-125e3c80-ac5a-11e8-9c31-006f2a0f7b60.png)

**Comment by sergey48k** [comment]
Sorry about it. Your profile was created just fine: 
https://sourcerer.io/oresoftware , but it looks like something else is going on. We will investigate and let you know.

**Comment by ORESoftware** [comment]
yeah from what I can tell, Github was provisioning something and wasnt
ready for Sourcerer...maybe a timeout.

I think there is a better way to do Oauth maybe. Gitter has good
integration with Gihub, Travis and CircleCI too.

**Comment by yandzee** [comment]
You were trying to sign-in, and that didn't perform signup if in that moment you had no sourcerer account. Now it's fixed.
