### ISSUE TITLE
Overview shows work done with `q`

### ISSUE THREAD

**Issue by alichtman** [sourcerer-io/sourcerer-app#343]
<img width="828" alt="image" src="https://user-images.githubusercontent.com/20600565/44944594-5ad34280-ad9f-11e8-8501-51a5b4d53e37.png">

https://sourcerer.io/alichtman

**Comment by sergey48k** [comment]
hi @alichtman ,

Could you provide more details?

**Comment by alichtman** [comment]
I don't know what other details to provide. I've never done work in a language, or with a library, called `q`

**Comment by sergey48k** [comment]
Ah, now it makes sense. Thank you!
S.

**Comment by anatolystansler** [comment]
Hi @alichtman!

Problem was fixed, thank you for reporting it.
