### ISSUE TITLE
Duplicate Vue

### ISSUE THREAD

**Issue by Kristories** [sourcerer-io/sourcerer-app#348]
Hello, I'm curious for Sourcerer stats. Is this intentional or not? (Same commits, different LOC)

![screen shot 2018-09-15 at 23 23 14](https://user-images.githubusercontent.com/774338/45588450-2636bd80-b93f-11e8-823f-2d61a570868f.png)

![screen shot 2018-09-15 at 23 27 27](https://user-images.githubusercontent.com/774338/45588451-2a62db00-b93f-11e8-9001-f35cd3595ae5.png)
![screen shot 2018-09-15 at 23 27 35](https://user-images.githubusercontent.com/774338/45588452-2cc53500-b93f-11e8-8878-2792bbedf6d7.png)

**Comment by anatolystansler** [comment]
Hi @Kristories!

This is a bug, we will investigate it. Thank you for reporting the problem.

**Comment by yaronskaya** [comment]
Fixed.
