### ISSUE TITLE
Lack of Windows install instructions

### ISSUE THREAD

**Issue by wojtekmaj** [sourcerer-io/sourcerer-app#352]
On this page: https://sourcerer.io/howitworks#app there's only a link to download a source code or an instruction to run `curl -s https://sourcerer.io/app/install | bash` command. This, however, doesn't work on Windows. What am I supposed to do to install the app on Windows?

**Comment by subramanya** [comment]
Hi wojtekmaj,
I have installed gitbash on windows that allows me to run unix commands on windows. Install gitbash for windows from here https://gitforwindows.org/.
See the sample run of  curl -s https://sourcerer.io/app/install | bash:M1047999@A2ML28411 MINGW64 ~/Documents/Sample-project/AEMMaven13/core
$  curl -s https://sourcerer.io/app/install |bash
Installing sourcerer app..
We installed app to ~/.sourcerer/sourcerer.
You can add it to $PATH or run specified command to finish installation:
sudo ln -s /c/Users/.sourcerer/sourcerer /usr/local/bin/sourcerer
Then run sourcerer to start hashing your repos!

**Comment by sergey48k** [comment]
Hi @wojtekmaj ,

I will update Windows instructions shortly.

**Comment by arturmamedov** [comment]
Okay i understood that my `/usr/local/bin/sourcerer` is `C:/Windows/System32`
But now when i run `sourcerer` it ask me with wich app i want to open it... what i need to do?

**Comment by JoshuaVandergriff** [comment]
Hey there everyone. I know this may seem like a generally older thread, however I am asking for some kindness to a new practitioner. How exactly do I connect and actively display my Github information? I know this may not work properly as i do not have much on my Github profile (I am just starting out as a Bootcamp student) however I want to get it set up now so it logs over the next 1.25 years as I progress through my curriculum.

**Comment by sergey48k** [comment]
hi @JoshuaVandergriff ,

If your repos are public, you can just login to sourcerer with github: https://sourcerer.io/start

S.

**Comment by sergey48k** [comment]
But if you want to do the local repos, just follow the instructions above by @mutiemule

**Comment by raa-zez** [comment]
When I run `java -jar sourcerer.jar`, getting the error message `Error: Invalid or corrupt jarfile sourcerer.jar`. How to fix this issue?

**Comment by sergey48k** [comment]
@yaronskaya what do you think? wrong java version?

**Comment by yaronskaya** [comment]
@raa-zez what is your java version?

**Comment by prabhuSub** [comment]
> In windows, sourcerer is installed at `C:\Users\windowsuser\.sourcerer`
> You can install sourcerer in windows by using git bash then run the command `curl -s https://sourcerer.io/app/install | bash`
> After installing, to run sourcerer, run the following command `java -jar sourcerer.jar`
> Ensure JAVA PATH is set up well in your environment variables (You should also be using the latest version of JDK).
> 
> Once you run `java -jar sourcerer.jar`, enter your username and password. (These are sent to your email. Incase they were not sent when you signed up to Sourcerer, head to **https://sourcerer.io** then reset your password using the **Forgot** option)
> 
> Now copy your repo path and add it.

Hi @mutiemule ,
Awesome! That worked. Any example on how to specify the repos?

**Comment by iamsainikhil** [comment]
@prabhuSub 

Steps:
1. Start the Sourcerer App & specify the repositories folder(s) on your machine
![sourcerer_app](https://user-images.githubusercontent.com/21148072/99892957-e23f5180-2c48-11eb-8ddd-c05fc5a3bb73.png)

2. Track the projects (you have the choice to whether hash[count] your contributions for a project)
![sourcerer_app_tracking_projects](https://user-images.githubusercontent.com/21148072/99892976-19adfe00-2c49-11eb-8f82-916a68f49a5e.png)

3. Finished Hashing your contributions (commits)
![sourcerer_app_finished_hashing](https://user-images.githubusercontent.com/21148072/99892998-45c97f00-2c49-11eb-8a55-b9cc8f053c9a.png)

4. Finished tracking projects
![sourcerer_app_finished_tracking_projects](https://user-images.githubusercontent.com/21148072/99892991-30eceb80-2c49-11eb-9319-90009c495186.png)

Finally, the stats take a while to show up on your profile depending on how many projects you added for tracking.

For any help related to the sourcerer app, below are the available commands 
or simple type `java -jar sourcerer.jar --help`

![sourcerer_app_help](https://user-images.githubusercontent.com/21148072/99893046-9ccf5400-2c49-11eb-9d5a-3daf4c585dbc.png)

**Comment by Yue-Q** [comment]
I have run      curl -s https://sourcerer.io/app/install | bash 
on my gitbash, (I am using Windows 10.0.18363, so I have installed cRUL)
However, I could not see any installation process, and I can not found any file named .sourcerer under my C:/Users/windowsUserName

Does anyone have the same problem as me?
![error](https://user-images.githubusercontent.com/45703282/101872240-86326380-3b4a-11eb-8f3f-47941d729f86.PNG)

**Comment by iamsainikhil** [comment]
@Yue-Q don't worry about it. Sourcerer had shutdown its services.

https://github.com/sourcerer-io/sourcerer-app/issues/632#issue-755331385

**Comment by Yue-Q** [comment]
> @Yue-Q don't worry about it. Sourcerer had shutdown its services.
> 
> [#632 (comment)](https://github.com/sourcerer-io/sourcerer-app/issues/632#issue-755331385)

Thanks for your update, sorry to see sourcerer.io has gone
