### ISSUE TITLE
Text written in About section has disappeared

### ISSUE THREAD

**Issue by Aecasorg** [sourcerer-io/sourcerer-app#354]
I wrote some really nice text in the About section and when I came back a couple of days later to copy it to something else it was all gone. I can't remember what I wrote now... 

Saving/storage always needs to be reliable.

**Comment by sergey48k** [comment]
Hi @Aecasorg 

Sorry about this!

@yandzee : could you please take a look?

**Comment by yandzee** [comment]
Sure

**Comment by yandzee** [comment]
We currently have a limit for this text in 1024 bytes. We will increase this soon.

**Comment by sergey48k** [comment]
Regardless of the limit, it should not let users enter more than it can
save.

**Comment by yandzee** [comment]
Fixed
