### ISSUE TITLE
Server error when opening a profile

### ISSUE THREAD

**Issue by alexxxdev** [sourcerer-io/sourcerer-app#360]
For some time now I constantly watch the"Server error when trying to access your profile (https://sourcerer.io/alexxxdev), although many other profiles open without problems
![image](https://user-images.githubusercontent.com/975579/46448118-863aba00-c7af-11e8-88d6-8b7d5121c145.png)

**Comment by alexxxdev** [comment]
Can anyone help solve the problem?

**Comment by sergey48k** [comment]
@anatolystansler , @yandzee  : could you please look into this?

**Comment by anatolystansler** [comment]
Hi @alexxxdev!

We fixed an issue with your profile. Sorry for a long wait.

**Comment by alexxxdev** [comment]
I get it again error(
