### ISSUE TITLE
Doesn't count all public repos

### ISSUE THREAD

**Issue by FredHappyface** [sourcerer-io/sourcerer-app#363]
It seems to recognise all of my public repositories (29 at the moment) however only provides analytics for 11 of these

**Comment by FredHappyface** [comment]
Closing and reopening the account seems to have fixed this issue

**Comment by ssbarnea** [comment]
I still find the statement true as it seems to miss indexing http://github.com/openstack/ and https://github.com/openstack-infra organizations which are public and really active.

**Comment by tuliobluz** [comment]
I'm facing the same problem, I have five repo, but It is showing just one. I tried to create a new account, but It has happened the same problem.

**Comment by FredHappyface** [comment]
Just an update on this, after closing and reopening the account. This issue is fixed for me

**Comment by FredHappyface** [comment]
Seems to be resolved so I'm going to close this
