### ISSUE TITLE
Help: Could not cartridge installation sourcerer-app

### ISSUE THREAD

**Issue by areisrosa** [sourcerer-io/sourcerer-app#364]
Hey, guys 

I performed curl -s https://sourcerer.io/app/install | bash has created the `.sourcerer` file that contains **sourcerer** and **sourcerer.jar**. 

But when execulto the ./sourcerer or sourcerer. The terminal displays the following message:
**Remark**: I did this too: sudo ln -s $HOME/.sourcerer/sourcerer /usr/local/bin/sourcerer

```sh
$ sourcerer
Unrecognized option: --add-modules
Error: Could not create the Java Virtual Machine.
Error: A Fatal exception has occurred. Program will exit.
```
Important Information
================
**O. S**: Debian 9 stretch
**Terminal**: Mate Desktop Environment 1.16.2
**Shell**: Zsh with On-My-Zsh

```sh
$ java --version
OpenJDK version "1.8.0_181 "
OpenJDK Runtime Environment (Build 1.8.0 _181-8u181-B13-1 ~ deb9u1-B13)
OPENJDK 64-Bit Server VM (Build 25,181-B13, Mixed mode)
```
```sh
$ javac --version
Javac 1.8.0_181
```
Can someone help me please?

**Comment by asurkov** [comment]
Should be fixed in #365 PR. Are there any extra steps required to update the installation script at https://sourcerer.io/app/install?

**Comment by areisrosa** [comment]
@asurkov great job. It worked. :+1:
Thank you very munch. :)

**Comment by asurkov** [comment]
glad to hear this :)
