### ISSUE TITLE
Add Flutter Projects to libraries

### ISSUE THREAD

**Issue by Bera** [sourcerer-io/sourcerer-app#383]
Projects made with Flutter doesn't show  in the website also dart projects may be

**Comment by sergey48k** [comment]
Hi @Bera ,

Thank you for the suggestion. The fastest way to see your favorite library or framework on sourcerer is to file a pull request to https://github.com/sourcerer-io/awesome-libraries/tree/master/libs .

Best,
Sergey

**Comment by Bera** [comment]
Hi Sergey

Unfortunately, until now, Sourcerer isn't allowing to add flutter projects yet.

**Comment by yaronskaya** [comment]
Hi @Bera, which of your repositories use flutter?

**Comment by Bera** [comment]
Hi @yaronskaya these are repos with flutter

https://github.com/Bera/eval-bloc-pattern-login-widget
https://github.com/Bera/animaflu


![image](https://user-images.githubusercontent.com/43844/48899695-6af73d00-ee37-11e8-99a9-77886c169b54.png)

But after updating my github profile new repos aren`t added 

![image](https://user-images.githubusercontent.com/43844/48899734-84988480-ee37-11e8-860c-a1c26a606190.png)

Neither Dart language or Flutter libraries are added

![image](https://user-images.githubusercontent.com/43844/48899815-c0cbe500-ee37-11e8-9ac7-fb50113d25e6.png)

Sometimes after update the github profile this application crashes

**Comment by yaronskaya** [comment]
@Bera looks like you didn't specified emails used in these repos. You can add them in Settings and then update your profile again.

**Comment by yaronskaya** [comment]
Your commits are with email "bmoura@produban.com.br" in the repo animaflu for example.

**Comment by Bera** [comment]
Thanks @yaronskaya 

Now I correct the email but Flutter still not recognized yet in the technology panel 

![image](https://user-images.githubusercontent.com/43844/49498793-52cde780-f853-11e8-888a-18d4e6118302.png)

**Comment by Bera** [comment]
Now it's working like a charm

![image](https://user-images.githubusercontent.com/43844/49588408-c18f6b80-f94d-11e8-99f2-540d852ede35.png)

![image](https://user-images.githubusercontent.com/43844/49588443-d7049580-f94d-11e8-8746-d1ead7f1452f.png)

![image](https://user-images.githubusercontent.com/43844/49588501-ff8c8f80-f94d-11e8-807e-e03257cf1404.png)

**Comment by yaronskaya** [comment]
Looks great @Bera 👍

**Comment by Bera** [comment]
https://www.reddit.com/r/FlutterDev/comments/a3o7al/sourcerer_app_now_supports_dart_and_flutter/
