### ISSUE TITLE
name private repos

### ISSUE THREAD

**Issue by jfcieslak** [sourcerer-io/sourcerer-app#391]
Private repos, when added manually, appear to have no names, when listed on sourcerer.io profile. Can that be changed? Is there a way to manually name these repos? Or is this intentional? It could be useful mainly for keeping track of the repo list.

**Comment by sergey48k** [comment]
Hi @jfcieslak ,

It is intentional; we don't want any proprietary info made public by accident. What you can do is you can click Edit icon on the repo section and enter something as a repo one-liner.

**Comment by jfcieslak** [comment]
@sergey48k I understand that this is intentional, I guess this can be closed then? Maybe for a feature suggestion: perhaps repos can be labeled through cli when adding them? like:
`sourcerer add [REPO] [LABEL]`. Anyway, amazing project!
