### ISSUE TITLE
Delete all data

### ISSUE THREAD

**Issue by Xe** [sourcerer-io/sourcerer-app#399]
I have looked and can't find a way to have a user unconditionally have all of their data deleted from this service. I made a mistake authorizing this app and want to opt out. I can't find a way to do this in the app, so I am making a ticket here hoping that this will reach someone who can comply with this request.

Thank you and be well.

**Comment by sergey48k** [comment]
Hi @Xe ,

You can delete your account by clicking 'here' link at https://sourcerer.io/settings#account . See attached screenshot.

<img width="609" alt="image" src="https://user-images.githubusercontent.com/20287615/47988636-d03af680-e0f3-11e8-907c-60fbb12bd213.png">
