### ISSUE TITLE
I cannot see my profile

### ISSUE THREAD

**Issue by Dalgona** [sourcerer-io/sourcerer-app#401]
Probably related to, or a duplicate of #360, which has been fixed, but the same error happens when trying to open my profile. (https://sourcerer.io/dalgona)

cURL-ing the URL gave me this JSON:

```json
{
  "status": 500,
  "message": "TypeError: template is not a function",
  "name": "NuxtServerError"
}
```

**Comment by anatolystansler** [comment]
Hi @Dalgona!

Fixed

**Comment by yandzee** [comment]
Fixed
