### ISSUE TITLE
"Your coworker has joined" emails

### ISSUE THREAD

**Issue by jaywink** [sourcerer-io/sourcerer-app#406]
Hi crew,

I started getting "your coworker has just joined" emails from repositories where I have contributed something, for example `awesome-vue`. This is odd since none of these people are my coworkers ;)

Aside from the incorrect message content which is not that critical, it would be nice to opt-out of these emails via an unsubscribe link or failing that the settings on the site.

Thanks for the awesome site!

**Comment by jozefizso** [comment]
I cannot unsubscribe from these spammy emails.

**Comment by osilla** [comment]
@jozefizso @jaywink We're so sorry for this.  The co-worker emails we pushed out had several bugs in it and of coarse no way to unsubscribe.  We've disabled the feature and are working on fixes.

**Comment by jaywink** [comment]
Thanks! No worries, no big deal. Thanks for promptly dealing with it!
