### ISSUE TITLE
Scan branches other than master

### ISSUE THREAD

**Issue by Nekromancer** [sourcerer-io/sourcerer-app#422]
Is there a reason why are you scanning only master branches of repositories? I think a lot of code is sitting on develop. I know (and i work on one) some repositories that have develop set as default branch on GitHub. Maybe you should consider scanning default branch? I'm not sure if you can get that info from GitHub api though

**Comment by anatolystansler** [comment]
Feel free to reopen an issue if problem still exists.

**Comment by Nekromancer** [comment]
I'm trying to scan my private repo which have all of it's code on develop branch. But only master get scanned. Can i force `sourcerer` app to scan particular branch?
