### ISSUE TITLE
Webapp profiles broken?

### ISSUE THREAD

**Issue by joeblackwaslike** [sourcerer-io/sourcerer-app#426]
Every time I've tried to visit my profile @ https://sourcerer.io/joeblackwaslike I get the following:

```
Server error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.
````

I thought initially that maybe this was temporary, but it's been like this for about 4 days now.

Does anyone else have this problem or is it just me?  This looks like a cool project and can't wait to see it, but it's kind of a bummer. :(

**Comment by sergey48k** [comment]
@yandzee please help ASAP, seems like an isolated problem but it's not temporary. something is broken for https://sourcerer.io/joeblackwaslike

**Comment by TomOrth** [comment]
This also happened to me. If you go to sourcerer.io/tomorth

**Comment by yandzee** [comment]
Yep, im aware of this issue. Fix will be deployed soon.

**Comment by yandzee** [comment]
@TomOrth @joeblackwaslike your profiles are working now
