### ISSUE TITLE
Processed repos but shows no stats

### ISSUE THREAD

**Issue by Whatapalaver** [sourcerer-io/sourcerer-app#427]
I signed up to use public data via GitHub.
It has successfully pulled my profile data but isn't showing anything for my stats.
I get an email saying my profile is ready but if that is the case - it's not very exciting.
https://sourcerer.io/whatapalaver
Thanks

**Comment by anatolystansler** [comment]
Hi @Whatapalaver!
Sorry for a late response, we've finally fixed the problem and updated your profile, you can use it now.

Related to #483
