### ISSUE TITLE
Can't start on Debian / OpenJDK 11

### ISSUE THREAD

**Issue by toupeira** [sourcerer-io/sourcerer-app#430]
I just set up the Sourcerer app and ran into this error:

```sh
$ sourcerer
Error occurred during initialization of boot layer
java.lang.module.FindException: Module java.activation not found
```

I saw there's a package `libactivation-java` in Debian, installing it didn't help though since it contains a different module "java**x**.activation".

But removing `--add-modules java.activation` from the `sourcerer` wrapper script did the trick and I can now successfully use the app.

Not sure if this is issue is specific to Debian sid or OpenJDK 11.

I'm using these packages:

```
ii  openjdk-11-jdk:amd64          11.0.1+13-3  amd64        OpenJDK Development Kit (JDK)
ii  openjdk-11-jdk-headless:amd64 11.0.1+13-3  amd64        OpenJDK Development Kit (JDK) (headless)
ii  openjdk-11-jre:amd64          11.0.1+13-3  amd64        OpenJDK Java runtime, using Hotspot JIT
ii  openjdk-11-jre-headless:amd64 11.0.1+13-3  amd64        OpenJDK Java runtime, using Hotspot JIT (headless)
```

**Comment by asurkov** [comment]
it should be fixed now #431

**Comment by toupeira** [comment]
@asurkov looks good, thanks! :+1:

**Comment by asurkov** [comment]
@toupeira glad to hear, thanks for checking out!
