### ISSUE TITLE
[Possible duplicate] No data displayed on my profile.

### ISSUE THREAD

**Issue by VentGrey** [sourcerer-io/sourcerer-app#434]
I think this is a far known issue by now. But despite my efforts I can't seem to figure out what is happening to my sourcerer account, this thing happened 1 or 2 months ago, at first some languages were "dissapearing" one by one, until one final "Refresh Github repos" click where my profile was completely empty.

Now, I've tried several things in this time:

* Deleting my sourcerer account
* Using the Kotlin script provided in this repo
* Unlink & re-link my GitHub account
* Spam the "Update repos" button (Desperate times require desperate measures)
* Waiting to see if any profile issues is closed or answered
* Commiting to old repositories.

Just for the sake of patience of other users who also had/have this issue.

Is this a regression in production? Are you somehow updating the way sourcerer counts contributions? Why are some users  not affected by this issue? 

I'm looking forward to your answer, I'll be glad to provide details or to take measures if something is wrong on my side :)

**Comment by sergey48k** [comment]
@anatolystansler could you take a look?

**Comment by VentGrey** [comment]
Bump issue (?)
