### ISSUE TITLE
I do a lot of XML (!?!?)

### ISSUE THREAD

**Issue by france193** [sourcerer-io/sourcerer-app#435]
Looking at my profile (https://sourcerer.io/france193) it seems that i have the madjority of code as XML. This is so strange, it seems that the code of my repos is misunderstood.
Any checks or solutions?

Thank you!

**Comment by sergey48k** [comment]
@france193 : we will look into it. Meantime, you can click Edit icon (pencil) and hide XML, as a temp solution.

**Comment by yaronskaya** [comment]
Fixed.
