### ISSUE TITLE
Server error when opening a profile

### ISSUE THREAD

**Issue by alexxxdev** [sourcerer-io/sourcerer-app#440]
For some time now I constantly watch the"Server error when trying to access your profile (https://sourcerer.io/alexxxdev), although many other profiles open without problems

**Comment by anatolystansler** [comment]
Hi @alexxxdev!

Fixed. Thank you for creating an issue.

**Comment by alexxxdev** [comment]
> Hi @alexxxdev!
> 
> Fixed. Thank you for creating an issue.

thx!
