### ISSUE TITLE
Changed username on Github doesn't get updated on sorcerer.io

### ISSUE THREAD

**Issue by TylerLeonhardt** [sourcerer-io/sourcerer-app#450]
Hi there - love the product!

I recently changed my Github username:

tylerl0706 -> TylerLeonhardt

But my sourcerer profile doesn't seem to reflect this change when I re-login with GitHub:

https://github.com/TylerLeonhardt
https://sourcerer.io/tylerl0706

I also tried manually changing it in the bio but sadly no luck on that front. Any chance you could add support for this?

Or potentially delete my current data so I can re-login fresh?

**Comment by yandzee** [comment]
Hi!

We are glad to hear that you love it :)
The feature you are asking for is currently in progress. I will report here soon.

**Comment by TylerLeonhardt** [comment]
It worked! Thanks @yandzee :)
