### ISSUE TITLE
Do we need gender pronouns in the "invite others" copy?

### ISSUE THREAD

**Issue by leojkwan** [sourcerer-io/sourcerer-app#458]
I'm guessing the copy is based on gender data provided by Github, but is Sourcerer defaulting to "his"?

![screen shot 2019-01-20 at 12 01 24 pm](https://user-images.githubusercontent.com/10264891/51442504-4ee31100-1cab-11e9-9918-9bb83354b20a.png)

**Comment by sergey48k** [comment]
Wow this is really bad. Not sure how we overlooked it. @yandzee : let's remove 'his' ("Invite to unlock fun facts")

thanks @leojkwan !

**Comment by leojkwan** [comment]
no problem! Thanks for building a great tool team!

**Comment by yandzee** [comment]
Done.
