### ISSUE TITLE
Sourcerer profile down

### ISSUE THREAD

**Issue by lmsanch** [sourcerer-io/sourcerer-app#460]
As in the title, my sourcerer profile is gone. "An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details."

**Comment by sergey48k** [comment]
sorry about that. we are looking.

**Comment by lmsanch** [comment]
Thank you Sergey! Profile seems to be up again, but all the badges are missing. A bug?

**Comment by sergey48k** [comment]
We rolled back some changes to restore it quickly, will address this
tomorrow.
S.
