### ISSUE TITLE
Badges, years using specific programming languages, etc.

### ISSUE THREAD

**Issue by lmsanch** [sourcerer-io/sourcerer-app#461]
First of all, congrats to all the developers of sourcerer. Excellent application. Anyway, the issue is the info I had in my badges is gone, and now I can only see "years using X" , etc., which is not compatible with the timeline charts. I.ex, the time line shows some of my python repos as far back as 2012, but the badges say that I have been using python for only 2 years, etc.

**Comment by sergey48k** [comment]
Hi @lmsanch ,

We will double check your profile, but the change we recently done was to count commit for 'top-developer' badges from repos with 5 or more contributors. The thinking was a commit made in a team is more valuable than a commit made in a repo with one contributor. But since you contributed since 2012, something must be broken in the process. We'll debug. Thank you

**Comment by lmsanch** [comment]
Thank you @sergey48k . Very interesting observation..I am fascinated by Sourcerer because the local app allows me to account for my private repos. I have been coding since 1982, and since  1998s, I have been coding mostly for banks/hedge funds etc., and nothing is put in  public repos, but private. Most of the time, coding alone is the norm in order to keep proprietary info compartmentalized. The "top badges" are great; so definitely I would like to "earn them back", if there is a way. May I suggest something? maybe 5 years or more coding alone earns you badges also.; or maybe a "high reputation" in StackOverflow (2000 points or more?) or some commits or lines of code threshold; or some other "filter" like that. Maybe you should allow your users specify their SO profile if they have any, anyway...I think the more info you capture about Sourcerer users, the  more valuable the app becomes (i.e.: My StackOverflow profile is here: https://stackoverflow.com/users/1290147/luis-miguel).
Again, kudos for the excellent development of sourcerer! Cheers

**Comment by yaronskaya** [comment]
Hi @lmsanch! 
Could you please point to your profile at Sourcerer?

**Comment by lmsanch** [comment]
Sure! https://sourcerer.io/lmsanch

**Comment by yaronskaya** [comment]
Hi @lmsanch. We slightly updated the formula for badges. Now it works with repositories of small teams too. I hope your profile looks better now.

Still investigating the issue with years.

**Comment by yaronskaya** [comment]
Updated calculation of the number of years is in production.
