### ISSUE TITLE
Write with extension .re (Reason) but detect as Javascript

### ISSUE THREAD

**Issue by blubMe** [sourcerer-io/sourcerer-app#462]
is sourcerer support for Reason / Ocaml lang ? on my github repo its detect using Ocaml lang. But in sourcerer its detected using Javascript lang & immutable. I hope if sourcerer support Ocaml its will be great.

My repos : https://github.com/blubMe/belajar-reason ( detected using Ocaml )

My repos at sourcerer :
![screen shot 2019-01-23 at 15 02 52](https://user-images.githubusercontent.com/17546686/51591587-041dff00-1f20-11e9-907d-fdf77d19bae4.png)

Thanks 👍

**Comment by yaronskaya** [comment]
Hi @blubMe!
Could you please update your profile? Reason should be detected as OCaml now.

Also, you can help us improve the app by adding some libraries for OCaml to [sourcerer-io/awesome-libraries](https://github.com/sourcerer-io/awesome-libraries).

**Comment by blubMe** [comment]
Thanks , i've update my profile and now detected as OCaml. 👍
