### ISSUE TITLE
Logging issues when login with github

### ISSUE THREAD

**Issue by Peuapeu2019** [sourcerer-io/sourcerer-app#464]
Having issue login in when using github login . Other user with username Wise12 is logged in instead of my profile.  Find screenshot below. 

![image](https://user-images.githubusercontent.com/45409364/51794297-a4cd2280-219d-11e9-8f81-f01a869f5281.png)

**Comment by yandzee** [comment]
@Peuapeu2019 we did an appropriate fix, so it should be ok now, try to signup again
