### ISSUE TITLE
Error Installing on Mac-osx

### ISSUE THREAD

**Issue by ericgiambattista** [sourcerer-io/sourcerer-app#467]
When I run $sourcerer, I get the following message:

Installed  version of Java is not supported.
Sourcerer requires JDK 8+ installed on the system. You can download it from:
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

After downloading at the above link,

$java -version

yields:

java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

[Edited/added]: However, when I run sourcerer again, I am continuing to get the same "Installed  version of Java is not supported." error.

Any idea what is going wrong?

**Comment by sergey48k** [comment]
Hi @ericgiambattista ,

I am a bit confused. Sourcerer did not work because you did not have Java 8. Then you installed Java 8. But what happens then? Do you see the same message when run sourcerer?

**Comment by ericgiambattista** [comment]
Got this fixed with $brew update gawk

(https://stackoverflow.com/questions/49457773/dyld-library-not-loaded-usr-local-lib-libmpfr-4-dylib)

Full error message (which I should have posted originally) was:

dyld: Library not loaded: /usr/local/opt/mpfr/lib/libmpfr.4.dylib
  Referenced from: /usr/local/bin/awk
  Reason: image not found
Installed  version of Java is not supported.
Sourcerer requires JDK 8+ installed on the system. You can download it from:
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Thanks @sergey48k
