### ISSUE TITLE
My profile stats are not getting displayed even after multiple scans. I deleted my account and signed in again using GitHub but problem still persists. Any help will be appreciated. Great tool indeed!

### ISSUE THREAD

**Issue by TheKetan2** [sourcerer-io/sourcerer-app#470]

**Comment by TheKetan2** [comment]
Profile link: https://sourcerer.io/theketan2

**Comment by sergey48k** [comment]
@anatolystansler - could you take a look?

**Comment by TheKetan2** [comment]
> @anatolystansler - could you take a look?

Is it a bug or is there some problem on my part?

**Comment by anatolystansler** [comment]
Hi @TheKetan2!
Problem is fixed now. I've updated your profile. Thank you for reporting and issue!

Refreshing of a profile should help now if someone encountered the same problem before.

Related to #483

**Comment by TheKetan2** [comment]
It's working now, Thank You very much.

> Hi @TheKetan2!
> Problem is fixed now. I've updated your profile. Thank you for reporting and issue!
> 
> Refreshing of a profile should help now if someone encountered the same problem before.
> 
> Related to #483
