### ISSUE TITLE
Cannot change my picture

### ISSUE THREAD

**Issue by janvanveldhuizen** [sourcerer-io/sourcerer-app#471]
When I want to change my picture the Save button is somewhere outside the window, and there is no scroll bar...

**Comment by anatolystansler** [comment]
Hi @janvanveldhuizen!
Sorry for the late response. What browser and platform do you use?

**Comment by janvanveldhuizen** [comment]
I tried Firefox and Edge.
![image](https://user-images.githubusercontent.com/43573150/54671480-4dd92f00-4af6-11e9-8525-5118b02983e6.png)

**Comment by janvanveldhuizen** [comment]
Sorry, closed it unintentionally

**Comment by yandzee** [comment]
Fixed.
