### ISSUE TITLE
Stats say I've contributed 745k LOC in 760 commits but I definitely don't average close to 1k LOC per commit

### ISSUE THREAD

**Issue by iansan5653** [sourcerer-io/sourcerer-app#472]
Pretty much what the title says. My profile stat for lines of code seems excessively high - almost all of my commits are less than 100 lines.

**Comment by kajchang** [comment]
For me, I think I've committed `node_modules` a few times, and technologies like `bootstrap` show up as 4k LOC and `jquery-validate` shows up as 11k so maybe there should be a check that excludes vendored / `node_modules` code.

**Comment by kajchang** [comment]
@yaronskaya was this removed globally? Because this type of filter would probably help.
https://github.com/sourcerer-io/sourcerer-app/issues/456#issuecomment-456038758

**Comment by iansan5653** [comment]
I think it might have something to do with submodules? Sourcerer says I contributed 500k lines in [this range](https://github.com/usf-avc/public-website/commits?author=iansan5653&since=2018-02-01&until=2018-03-01), but the biggest commits I can find are still only 20k lines ([here ](https://github.com/usf-avc/public-website/commit/87adcb310112befb21b19295c47ae1a29181a614) and [here](https://github.com/usf-avc/public-website/commit/2c8e841dd12a04189c683b00ed019b743a04250b))

**Comment by iansan5653** [comment]
Actually, never mind. Here's the 650k line commit https://github.com/usf-avc/public-website/commit/18a0f4c2d6be2feea346eefdc9ef62cfc8479a7b

**Comment by kajchang** [comment]
I worked on a repo without `node_modules` in `.gitignore` and when I added a dependency it added 200k LOC: https://github.com/rishinath4159/discord-app/commit/c3a1e7af22268a49711f5d334253b004221e35c3.

**Comment by yaronskaya** [comment]
Hi @kajchang. We updated the app so it doesn't count node_modules now.

**Comment by kajchang** [comment]
Thanks, it's working well for me now!

**Comment by iansan5653** [comment]
@yaronskaya Can this be reopened? My original issue was not fixed -- this commit (usf-avc/public-website@18a0f4c), for example, is 650,000 lines without involving node_modules. Could you set a maximum line limit per commit, or at least allow me to set one?

**Comment by iansan5653** [comment]
Actually, never mind. Looks like it is handled already and my profile hadn't updated.
