### ISSUE TITLE
Mismatch between fonts for "Followers" and "Following"

### ISSUE THREAD

**Issue by MikeColes** [sourcerer-io/sourcerer-app#475]
![image](https://user-images.githubusercontent.com/11658633/53183609-a1c12880-35c9-11e9-8eda-3975385ef03b.png)

I'm not sure if this is intentional or not. It looks like the attributes for the count of Followers and the count of Following is mismatched (slashed zero vs non-slashed zero).

**Comment by yandzee** [comment]
Fixed. Thank you!
