### ISSUE TITLE
missing repo details

### ISSUE THREAD

**Issue by PandiyanCool** [sourcerer-io/sourcerer-app#480]
I have 43 repos but it showing only details of 5 repos

Profile link:
https://sourcerer.io/pandiyancool

**Comment by anatolystansler** [comment]
Hi @PandiyanCool!

Thank you for creating an issue! I've updated your profile after latest fixes of processing algs. Your profile contains more repos now, but not all of 43. Here is why:

|Repo|Comment|
|---|---|
|csharp-practice|Presented|
|angular-clipboard|Presented|
|test-proj|Presented|
|pipeline-test|Presented|
|azure-pipeline-demo|Presented|
|BeingYoutuber|Presented|
|NationForesee|Presented|
|ngx-date-converter|Presented|
|pandiyan.cool|Presented|
|AzureConnect|Presented|
|EmployeeCorrelationApp|Presented|
|Udacity-Mobile-Web-Course|Presented|
|SnakeGame|Presented|
|Flames|Presented|
|PomodoroTimer|Presented|
|es6-practice|Presented|
|twitter-user-tagging|Presented|
|CSharp-Six-Practice|Presented|
|ProjectSeven|Presented|
|THF-Web|Presented|
|ElasticBridge|Presented|
|ElasticVisualizer|Presented|
|angular-practice|Presented|
|Assignment-DC|Presented|
|zeroclickinfo-goodies|Presented|
|cool-list | Only MD edits|
|AwesomeBlogs | Only MD edits|
|public-talks | Only binary edits|
|vivify | Only gitignore and MD edits|
|python-practice | Only gitignore edits|
|angular-4-practice | Only gitignore edits|
|thirukural | Only gitignore and yaml configs edits|
|aurelia-effect | Only MD edits|
|ng-packagr | No contributions|
|awesome-python | No contributions|
|contact-manager | No contributions|
|pipelines-javascript | No contributions|
|zeroclickinfo-spice | No contributions|
|task-mail | No contributions|
|gitignore | No contributions|
|Warden | No contributions|
|TypeScript | +300 MB, use the App to add this repo to your profile|
|elasticsearch | +300 MB, use the App to add this repo to your profile|

Sourcerer shows only repos that contain code stats in your commits from master (or default) branch. If your repo commits contain only text, config, or binary changes - repo will not be presented in the profile as it doesn't reflect your coding skills. We plan to introduce configs support in future though.

**Comment by PandiyanCool** [comment]
Thanks, thats helpful!
