### ISSUE TITLE
Repository is empty when it shouldn't be

### ISSUE THREAD

**Issue by ZapDos7** [sourcerer-io/sourcerer-app#483]
Hello. I visited the site, and created an account using GitHub. The site processed my repos but eventually came up with nothing, when it should display my public repos. 
Then, I tried the terminal/app method, using the code sent to me via email: I installed the app and the check performed informed me that all my repos had been scanned (even the private ones) and that my profile had been updated, yet it is still empty.
Am I doing something blatantly wrong? How can this be fixed? Thanks!

**Comment by anatolystansler** [comment]
Hello @ZapDos7! 
We had a bug on our server, your commits were not assigned to your profile. It's fixed now. Thank you for reporting an issue.
Feel free to use the app to add your closed source repo to the profile.

**Comment by ZapDos7** [comment]
Thank you so much! I have used the app already.
