### ISSUE TITLE
Not having access to an email accoun- from a previous job. What to do?

### ISSUE THREAD

**Issue by whoan** [sourcerer-io/sourcerer-app#494]
I don't have access to an email account from a previous job, so how can I confirm the account belongs to me?

**Comment by dan-compton** [comment]
I actually  have the same issue and I think it's going to be a common one.  One solution would be to verify your commits with PGP -- then you could prove that you were the committer regardless of email I think.  (e.g. export your public key, and sourcer.io executes a challenge using it).  

If the startup went under, you could buy the domain...

**Comment by aodj** [comment]
It's even worse than that in some cases, if you haven't configured git correctly and your commits come from the hostname: `alexander@Alexanders-MacBook-Air.local` for example.

Good luck validating that email address.

**Comment by kihonq** [comment]
@aodj I'm in the same boat bro 😭
