### ISSUE TITLE
I'm having trouble updating my github history on sorcerer.io

### ISSUE THREAD

**Issue by OtakuSenpai** [sourcerer-io/sourcerer-app#496]
Hey there, nice product you have got !
I currently commit files to my github from the cli git command, and somehow sorcerer.io can't check 
if both the accounts are same.

Sample : https://postimg.cc/fkzJrV0S

Can you please do something about it ? I'm really looking forward to using this service.

**Comment by OtakuSenpai** [comment]
Apparently I used a different email and the way github uses git config files to store the commits are quite bad for me. 
https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user
Can you do something about it? I have written quite a lot code, that I don't want to go to waste :frowning:

**Comment by sergey48k** [comment]
Hi @OtakuSenpai ,

Could you send an email to support@sourcerer.io and include both of your email addresses? We will look into it.

Best,
Sergey

**Comment by OtakuSenpai** [comment]
Thanks a lot man

**Comment by OtakuSenpai** [comment]
Sent the email.

**Comment by OtakuSenpai** [comment]
This is my off.avraneel@gmail.com (dont use it very much though).
The other one linked on my Github account is edu.avraneel@gmail.com.

And the one I actually had on the git config is this string "Find me on
Freenode".

Hope that helps,
Avra Neel.

**Comment by yaronskaya** [comment]
Hi @OtakuSenpai !
'Find me on Freenode' is not a valid email. So it is not stored in our databases. 
You can change email manually(see [guide](https://help.github.com/en/articles/changing-author-info)).
If you don't want to store emails on github then you can run sourcerer-app locally for a repo with updated git history.

**Comment by OtakuSenpai** [comment]
Thanks alot, did it and my profile seems fair enough.
Cheerios !!

**Comment by yaronskaya** [comment]
@OtakuSenpai cool 👍
