### ISSUE TITLE
Can't create account with old same github name

### ISSUE THREAD

**Issue by nfuhs** [sourcerer-io/sourcerer-app#501]
Hi,

I deleted my old github account nfuhs and now I'm using this one.

I can grant access to github:

![Github-2](https://user-images.githubusercontent.com/48379615/56090809-7a8b2700-5ea7-11e9-848a-d335105c14a2.png)

I deleted my old sourcerer.io account nfuhs and wanted to create a new one but if try to I only get this error message :

![sourcerer](https://user-images.githubusercontent.com/48379615/56090795-4ca5e280-5ea7-11e9-81e7-0f118fcc0683.png)

**Comment by sergey48k** [comment]
@anatolystansler could you help?
