### ISSUE TITLE
Build error in task :generateProto - Value 'directory '.../sourcerer-app/build/extracted-protos/main'' specified for property '$2' cannot be converted to a file

### ISSUE THREAD

**Issue by reuben** [sourcerer-io/sourcerer-app#504]
Gradle scan: https://scans.gradle.com/s/pbxnfb4bsjcdu

Seems to be a problem with protobuf-gradle-plugin, upgrading to 0.8.4 fixes the problem for me: https://github.com/gradle/gradle/issues/6877#issuecomment-424198125

**Comment by sergey48k** [comment]
@anatolystansler @yaronskaya : did we break something?

**Comment by sfat** [comment]
@yaronskaya , I think this can be closed since #540 was merged.
