### ISSUE TITLE
Server issues?

### ISSUE THREAD

**Issue by nfacha** [sourcerer-io/sourcerer-app#508]
![photo_2019-05-03_11-47-03](https://user-images.githubusercontent.com/8540172/57135562-5ed5bb00-6d99-11e9-8f3c-6d105661cfaa.jpg)

Not a network issue on my side, site works just fine.
The problem persists across multiple devices and geographically different networks.

**Comment by tsnowlan** [comment]
I haven't been able to connect for probably 3 weeks. Refresh github/gitlab from site also still times out for me, though.

**Comment by yaronskaya** [comment]
@tsnowlan did it finish processing? You can find it in Settings->Processing.

**Comment by yaronskaya** [comment]
@tsnowlan did it finish processing? You can find it in Settings->Processing.

**Comment by yaronskaya** [comment]
@tsnowlan is the processing finished properly? You can find it in Settings->Processing.
