### ISSUE TITLE
Private repos uploaded with success but not updating profile

### ISSUE THREAD

**Issue by lucianopereira86** [sourcerer-io/sourcerer-app#532]
Hello!
First of all, congratulations for this amazing tool.
My username is: lucianopereira86
I've uploaded many private repositories with Sourcerer app by following the steps described below.

- Used Git Bash to install Sourcerer with this command:
 curl -s https://sourcerer.io/app/install | bash  

- Opened the sourcerer folder:
C:\Users\luxcl\.sourcerer

- Ran this command with Powershell:
java -jar sourcerer.jar  

- Added the paths for my private repos:
C:\Users\luxcl\Desktop\BitBucket\MY-PROJECT

- Finally pressed Enter so the data could be processed and uploaded to my Sourcerer profile.

- To add more repos, I had to run the command for each one:
java -jar sourcerer.jar   add -a "C:\Users\luxcl\Desktop\BitBucket\MY-PROJECT"

Everything worked well in my laptop when I was processing my Bitbucket projects.
Then, when I was at the office doing the same with the other Bitbucket projects I had been working on, my profile was not updated by the Sourcerer app, although no error had occured during the  process.
I've tested it again in my laptop and the problem persists no matter which repo I use.
What can I do?

**Comment by yaronskaya** [comment]
Hi @lucianopereira86. Does it contain verified emails?

**Comment by lucianopereira86** [comment]
> Hi @lucianopereira86. Does it contain verified emails?

Yes. It contains.

**Comment by lucianopereira86** [comment]
x
