### ISSUE TITLE
Build Error: Some problems were found with the configuration of task ':generateProto'.

### ISSUE THREAD

**Issue by jaeyeonling** [sourcerer-io/sourcerer-app#537]
Gradle scan: https://scans.gradle.com/s/pqhpsczvqu4iu

I don't know what the problem is and I can't solve it with my ability.

**Comment by sfat** [comment]
I think it has to do with Gradle `5.6`.
Can you check if using `4.10.3` works fine?

**Comment by sfat** [comment]
@yaronskaya , I think this can be closed since #540 was merged.

**Comment by yaronskaya** [comment]
@sfat sure
