### ISSUE TITLE
Error "can't send uour data to server. Try again later."

### ISSUE THREAD

**Issue by brendonguedes** [sourcerer-io/sourcerer-app#541]
I am receiving the error message: Error "Can't send data to server. Try again later." right after syncing my Gihtub account with Sourcerer. I can not use due to the error mentioned.

**Comment by yaronskaya** [comment]
Hi @brendonguedes. Could you please try to sync github account again?

**Comment by brendonguedes** [comment]
Vi @yaronskaya. I will revoke the sync and do the process again.

**Comment by brendonguedes** [comment]
Hi @yaronskaya 
I did the process again and the error persisted.

**Comment by yaronskaya** [comment]
@brendonguedes could you please try once again?

**Comment by brendonguedes** [comment]
I tried again and it worked. You haven't uploaded my data and repositories yet but I received an email from confircak de creation di my profile. Thank you @yaronskaya

**Comment by brendonguedes** [comment]
error ceased after retries
