### ISSUE TITLE
Everytime Skipping entire repos

### ISSUE THREAD

**Issue by imhta** [sourcerer-io/sourcerer-app#543]
Whenever I tried to scan my GitHub profile, it scans and skipped the entire repos 

![image](https://user-images.githubusercontent.com/25448577/64550968-ad9bee80-d351-11e9-921f-dcc52cbef6d6.png)

**Comment by yaronskaya** [comment]
@imhta thank you for reporting that. Fixed the problem.

**Comment by imhta** [comment]
Now it working fine

**Comment by gerardoezequiel** [comment]
I have the same problem
![image](https://user-images.githubusercontent.com/34824185/115630336-c3c6aa80-a2fb-11eb-8999-6c470fc03013.png)

**Comment by WilliamRagstad** [comment]
Me too
![image](https://user-images.githubusercontent.com/41281398/129228499-3759f878-58d4-4548-b3ab-ca19f63e3e83.png)
