### ISSUE TITLE
Error while hashing

### ISSUE THREAD

**Issue by srihari-humbarwadi** [sourcerer-io/sourcerer-app#544]
Processing error on webapp and if i try to add the repository from local machine 
i get this message
```
[e] Error while hashing: it.optJSONArray("source") must not be null
```

**Comment by yaronskaya** [comment]
@srihari-humbarwadi thank you for submitting this. The problem is fixed in the latest version of sourcerer-app.

**Comment by srihari-humbarwadi** [comment]
Works fine now! Thanks
