### ISSUE TITLE
Sourcerer.io does not work with gitlab.gnome acounts.

### ISSUE THREAD

**Issue by VSevagen** [sourcerer-io/sourcerer-app#548]
I actually tried linking my gitlab profile to sourcerer but gitlab itself was not able to recognize my account.  I'm a gnome contributor and I have a gnome account for accessing my profile on gitlab. I know that some permissions might be required for accessing gnome accounts database but is there something else that can be done ?

**Comment by sergey48k** [comment]
Hi @VSevagen ,

Is this a private GitLab installation or is it gitlab.com?

**Comment by VSevagen** [comment]
It is not gitlab.com. It is actually gitlab.gnome.org and my account is a gnome account.

**Comment by CorruptComputer** [comment]
I don't think Sourcerer supports private GitLab and GitHub installations currently.

**Comment by VSevagen** [comment]
Ok. I'll close this then
