### ISSUE TITLE
No password mail

### ISSUE THREAD

**Issue by sparsh-99** [sourcerer-io/sourcerer-app#594]
I signed up to sourcerer app using Github and it clearly states that username and password will be sent to your primary email. 
But the issue is I didn't receive any such email from the sourcerer app.
Without a password, I am not been able to authorize my app in bash.

**Comment by AlexisTM** [comment]
Had the same issue: Just use "I forgot my password", you'll get a link to reset your password (actually set your password)

**Comment by antenore** [comment]
The same for me. I've the as @AlexisTM suggested and it works.

**Comment by sparsh-99** [comment]
Ok thank you @AlexisTM
