### ISSUE TITLE
Error: Invalid or corrupt jarfile ~/.sourcerer/sourcerer.jar

### ISSUE THREAD

**Issue by zhangchunsheng** [sourcerer-io/sourcerer-app#603]
java -jar ~/.sourcerer/sourcerer.jar
Error: Invalid or corrupt jarfile ~/.sourcerer/sourcerer.jar

java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

macOS 10.15.5

**Comment by vrdn-23** [comment]
Duplicate of #598

**Comment by zhangchunsheng** [comment]
I build it from source can work well.
