### ISSUE TITLE
All my github repo processing times out

### ISSUE THREAD

**Issue by Kittaru87** [sourcerer-io/sourcerer-app#605]
Trying to process my github repos and all of them time out - maybe I need to change a setting somewhere but not sure where 

<img width="664" alt="Screenshot 2020-07-14 at 12 01 36" src="https://user-images.githubusercontent.com/49982615/87418664-f784df00-c5c9-11ea-8274-93c7d2a944ea.png">

**Comment by stunn-areeb09** [comment]
I am facing the exact same issue what to do ??
