### ISSUE TITLE
Share button pointing to undefined fun_fact in url

### ISSUE THREAD

**Issue by gautamkrishnar** [sourcerer-io/sourcerer-app#613]
When I share something the share button is pointing to undefined in URL: https://sourcerer.io/gautamkrishnar?fun_fact=undefined

<img width="1026" alt="Screenshot 2020-09-01 at 3 45 08 PM" src="https://user-images.githubusercontent.com/8397274/91837909-5251c300-ec6a-11ea-8f89-4f1162119110.png">

**Comment by Zircoz** [comment]
I am unable to replicate this issue. Can you check if it still exists for you?

**Comment by gautamkrishnar** [comment]
@Zircoz looks like its fixed now. Thanks for the heads up.
