### ISSUE TITLE
Github refresh times out

### ISSUE THREAD

**Issue by sgr2848** [sourcerer-io/sourcerer-app#626]
Github & also the sourcerer-app refresh times out. Tried it few more times ,still no luck
![times](https://user-images.githubusercontent.com/37935221/98119316-8ea4d800-1ed4-11eb-87ff-233f6d1367fc.PNG)

**Comment by stephenleo** [comment]
same

**Comment by stephenleo** [comment]
facing the same issue

**Comment by jfgiraud** [comment]
Same issue too.

**Comment by BhishmDaslaniya** [comment]
Same issue...
