### ISSUE TITLE
Temporarily install https certificate

### ISSUE THREAD

**Issue by StyvenSoft** [sourcerer-io/sourcerer-app#635]
Can you temporarily install the certificate for the platform using [letsencrypt.org](https://letsencrypt.org/) or, by default, [certbot.eff.org](https://certbot.eff.org/) to keep the links of the users active? I see that your domain (sourcerer.io) expires 2021-06-18

**Comment by gautamkrishnar** [comment]
i also got the ssl error today

**Comment by gautamkrishnar** [comment]
Just saw #632
