### ISSUE TITLE
Missing #!/usr/bin/env bash in main bash script

### ISSUE THREAD

**Issue by hugogrochau** [sourcerer-io/sourcerer-app#87]
The bash script that gets downloaded to `~/.sourcerer/sourcerer` is missing the `#!/usr/bin/env bash` header.

So when I run `sourcerer` in my terminal I get the following error message:
```
Failed to execute process '/usr/local/bin/sourcerer'. Reason:
exec: Exec format error
The file '/usr/local/bin/sourcerer' is marked as an executable but could not be run by the operating system.
```

**Comment by sergey-surkov** [comment]
@anatolykislov should we close this?

**Comment by anatolykislov** [comment]
Yes. Thank you @hugogrochau !
