### ISSUE TITLE
Cannot find repo because stores relative path to repo

### ISSUE THREAD

**Issue by klapen** [sourcerer-io/sourcerer-app#92]
When I run sourcerer command, can not find repos I have because path is relative from where I run the 'add' command. So, to update all repos I need to run sourcerer command from all paths I used 'add' command.

**Comment by anatolykislov** [comment]
Hi, klapen! We've added support for relative paths in release 0.1.1 only 3 days ago. Before this update users of the app only had the option to specify absolute paths. Can you give an example of how you using the app and tell your Java and OS versions.

**Comment by anatolykislov** [comment]
Issue resolved.
